In [12]:
import pandas as pd

## 1) category, symbol: Primer registro es el actual y descar el default 200 registros (este tambien es el maximo).

In [13]:
from pybit.unified_trading import HTTP
session = HTTP()
data = session.get_funding_rate_history(
    category="linear",
    symbol="ETHPERP",
)

In [14]:
len(data["result"]["list"])

200

In [15]:
df = pd.DataFrame(data["result"]["list"])

In [22]:
df["fundingRateTimestamp"] = pd.to_datetime(
    pd.to_numeric(df["fundingRateTimestamp"]),
    unit="ms",
    utc=True
)

In [23]:
df

      symbol  fundingRate      fundingRateTimestamp
0    ETHPERP   0.00001329 2026-08-16 16:00:00+00:00
1    ETHPERP  -0.00000593 2026-08-16 08:00:00+00:00
2    ETHPERP  -0.00002782 2026-08-16 00:00:00+00:00
3    ETHPERP  -0.00002867 2026-08-15 16:00:00+00:00
4    ETHPERP   0.00000381 2026-08-15 08:00:00+00:00
..       ...          ...                       ...
195  ETHPERP   0.00000386 2026-06-12 16:00:00+00:00
196  ETHPERP  -0.00000638 2026-06-12 08:00:00+00:00
197  ETHPERP    0.0000542 2026-06-12 00:00:00+00:00
198  ETHPERP   0.00004559 2026-06-11 16:00:00+00:00
199  ETHPERP   0.00005861 2026-06-11 08:00:00+00:00

[200 rows x 3 columns]

## 2) category, symbol, start_time

si mandás startTime, también necesitás endTime

In [53]:
start_time = "2025-01-15 00:00:00"
end_time = "2025-01-31 23:59:59"


start_time = pd.to_datetime(start_time, utc=True)
start_time_ms = int(start_time.timestamp() * 1000)

end_time = pd.to_datetime(end_time, utc=True)
end_time_ms = int(end_time.timestamp() * 1000)

In [54]:
from pybit.unified_trading import HTTP
session = HTTP()
data = session.get_funding_rate_history(
    category="linear",
    symbol="BTCUSDT",
    startTime=start_time_ms,
    endTime=end_time_ms
)

In [55]:
df = pd.DataFrame(data["result"]["list"])

df["fundingRateTimestamp"] = pd.to_datetime(
    pd.to_numeric(df["fundingRateTimestamp"]),
    unit="ms",
    utc=True
)

In [56]:
df

     symbol  fundingRate      fundingRateTimestamp
0   BTCUSDT   0.00002658 2025-01-31 16:00:00+00:00
1   BTCUSDT   0.00003319 2025-01-31 08:00:00+00:00
2   BTCUSDT   0.00001241 2025-01-31 00:00:00+00:00
3   BTCUSDT       0.0001 2025-01-30 16:00:00+00:00
4   BTCUSDT       0.0001 2025-01-30 08:00:00+00:00
5   BTCUSDT   0.00007587 2025-01-30 00:00:00+00:00
6   BTCUSDT   0.00006486 2025-01-29 16:00:00+00:00
7   BTCUSDT   0.00001792 2025-01-29 08:00:00+00:00
8   BTCUSDT  -0.00002196 2025-01-29 00:00:00+00:00
9   BTCUSDT   0.00000659 2025-01-28 16:00:00+00:00
10  BTCUSDT   0.00005241 2025-01-28 08:00:00+00:00
11  BTCUSDT   0.00000581 2025-01-28 00:00:00+00:00
12  BTCUSDT   0.00001349 2025-01-27 16:00:00+00:00
13  BTCUSDT   0.00000253 2025-01-27 08:00:00+00:00
14  BTCUSDT       0.0001 2025-01-27 00:00:00+00:00
15  BTCUSDT       0.0001 2025-01-26 16:00:00+00:00
16  BTCUSDT       0.0001 2025-01-26 08:00:00+00:00
17  BTCUSDT       0.0001 2025-01-26 00:00:00+00:00
18  BTCUSDT   0.00005217 2025-01-25 16:00:00+00:00
19  BTCUSDT   0.00007472 2025-01-25 08:00:00+00:00
20  BTCUSDT       0.0001 2025-01-25 00:00:00+00:00
21  BTCUSDT       0.0001 2025-01-24 16:00:00+00:00
22  BTCUSDT   0.00009463 2025-01-24 08:00:00+00:00
23  BTCUSDT   0.00004386 2025-01-24 00:00:00+00:00
24  BTCUSDT       0.0001 2025-01-23 16:00:00+00:00
25  BTCUSDT       0.0001 2025-01-23 08:00:00+00:00
26  BTCUSDT       0.0001 2025-01-23 00:00:00+00:00
27  BTCUSDT       0.0001 2025-01-22 16:00:00+00:00
28  BTCUSDT       0.0001 2025-01-22 08:00:00+00:00
29  BTCUSDT       0.0001 2025-01-22 00:00:00+00:00
30  BTCUSDT       0.0001 2025-01-21 16:00:00+00:00
31  BTCUSDT       0.0001 2025-01-21 08:00:00+00:00
32  BTCUSDT       0.0001 2025-01-21 00:00:00+00:00
33  BTCUSDT       0.0001 2025-01-20 16:00:00+00:00
34  BTCUSDT       0.0001 2025-01-20 08:00:00+00:00
35  BTCUSDT       0.0001 2025-01-20 00:00:00+00:00
36  BTCUSDT       0.0001 2025-01-19 16:00:00+00:00
37  BTCUSDT       0.0001 2025-01-19 08:00:00+00:00
38  BTCUSDT       0.0001 2025-01-19 00:00:00+00:00
39  BTCUSDT       0.0001 2025-01-18 16:00:00+00:00
40  BTCUSDT       0.0001 2025-01-18 08:00:00+00:00
41  BTCUSDT   0.00009347 2025-01-18 00:00:00+00:00
42  BTCUSDT       0.0001 2025-01-17 16:00:00+00:00
43  BTCUSDT       0.0001 2025-01-17 08:00:00+00:00
44  BTCUSDT   0.00007555 2025-01-17 00:00:00+00:00
45  BTCUSDT       0.0001 2025-01-16 16:00:00+00:00
46  BTCUSDT       0.0001 2025-01-16 08:00:00+00:00
47  BTCUSDT   0.00005755 2025-01-16 00:00:00+00:00
48  BTCUSDT       0.0001 2025-01-15 16:00:00+00:00
49  BTCUSDT   0.00007032 2025-01-15 08:00:00+00:00
50  BTCUSDT   0.00005343 2025-01-15 00:00:00+00:00

## 3) category, symbol, end_time

En comparacion con el anterior aca no es necesario mandar startTime, pero si lo mandás, también necesitás endTime

In [42]:
start_time = "2025-01-15 00:00:00"
end_time = "2025-05-31 23:59:59"


start_time = pd.to_datetime(start_time, utc=True)
start_time_ms = int(start_time.timestamp() * 1000)

end_time = pd.to_datetime(end_time, utc=True)
end_time_ms = int(end_time.timestamp() * 1000)

In [44]:
from pybit.unified_trading import HTTP
session = HTTP()
data = session.get_funding_rate_history(
    category="linear",
    symbol="BTCUSDT",
    endTime=end_time_ms
)

In [47]:
data

{'retCode': 0,
 'retMsg': 'OK',
 'result': {'category': 'linear',
  'list': [{'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748707200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748678400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748649600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748620800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009532',
    'fundingRateTimestamp': '1748592000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748563200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001219',
    'fundingRateTimestamp': '1748534400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005974',
    'fundingRateTimestamp': '1748505600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007753',
    'fundingRateTimestamp': '1748476800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003181',
    'fundingRateTimestamp': '1748448000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00009526',
    'fundingRateTimestamp': '1748419200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00015645',
    'fundingRateTimestamp': '1748390400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002161',
    'fundingRateTimestamp': '1748361600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003247',
    'fundingRateTimestamp': '1748332800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748304000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009627',
    'fundingRateTimestamp': '1748275200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748246400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748217600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005451',
    'fundingRateTimestamp': '1748188800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1748160000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007422',
    'fundingRateTimestamp': '1748131200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004126',
    'fundingRateTimestamp': '1748102400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003436',
    'fundingRateTimestamp': '1748073600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002203',
    'fundingRateTimestamp': '1748044800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006534',
    'fundingRateTimestamp': '1748016000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005364',
    'fundingRateTimestamp': '1747987200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002206',
    'fundingRateTimestamp': '1747958400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009599',
    'fundingRateTimestamp': '1747929600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1747900800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007967',
    'fundingRateTimestamp': '1747872000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004226',
    'fundingRateTimestamp': '1747843200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007956',
    'fundingRateTimestamp': '1747814400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005146',
    'fundingRateTimestamp': '1747785600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0000044',
    'fundingRateTimestamp': '1747756800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007096',
    'fundingRateTimestamp': '1747728000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005531',
    'fundingRateTimestamp': '1747699200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005514',
    'fundingRateTimestamp': '1747670400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001146',
    'fundingRateTimestamp': '1747641600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1747612800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1747584000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003858',
    'fundingRateTimestamp': '1747555200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006156',
    'fundingRateTimestamp': '1747526400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002515',
    'fundingRateTimestamp': '1747497600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001723',
    'fundingRateTimestamp': '1747468800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000198',
    'fundingRateTimestamp': '1747440000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001606',
    'fundingRateTimestamp': '1747411200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003052',
    'fundingRateTimestamp': '1747382400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.0000084',
    'fundingRateTimestamp': '1747353600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0000338',
    'fundingRateTimestamp': '1747324800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002825',
    'fundingRateTimestamp': '1747296000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003808',
    'fundingRateTimestamp': '1747267200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001591',
    'fundingRateTimestamp': '1747238400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005778',
    'fundingRateTimestamp': '1747209600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002701',
    'fundingRateTimestamp': '1747180800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001231',
    'fundingRateTimestamp': '1747152000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004172',
    'fundingRateTimestamp': '1747123200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006072',
    'fundingRateTimestamp': '1747094400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007469',
    'fundingRateTimestamp': '1747065600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1747036800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1747008000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746979200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746950400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00008081',
    'fundingRateTimestamp': '1746921600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746892800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746864000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007638',
    'fundingRateTimestamp': '1746835200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005521',
    'fundingRateTimestamp': '1746806400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009238',
    'fundingRateTimestamp': '1746777600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746748800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746720000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1746691200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006604',
    'fundingRateTimestamp': '1746662400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001529',
    'fundingRateTimestamp': '1746633600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00008919',
    'fundingRateTimestamp': '1746604800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001728',
    'fundingRateTimestamp': '1746576000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002767',
    'fundingRateTimestamp': '1746547200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000683',
    'fundingRateTimestamp': '1746518400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.0000178',
    'fundingRateTimestamp': '1746489600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002175',
    'fundingRateTimestamp': '1746460800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006744',
    'fundingRateTimestamp': '1746432000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00007123',
    'fundingRateTimestamp': '1746403200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003498',
    'fundingRateTimestamp': '1746374400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004616',
    'fundingRateTimestamp': '1746345600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000312',
    'fundingRateTimestamp': '1746316800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00006553',
    'fundingRateTimestamp': '1746288000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001484',
    'fundingRateTimestamp': '1746259200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00011068',
    'fundingRateTimestamp': '1746230400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.0000303',
    'fundingRateTimestamp': '1746201600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002857',
    'fundingRateTimestamp': '1746172800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003523',
    'fundingRateTimestamp': '1746144000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003782',
    'fundingRateTimestamp': '1746115200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005255',
    'fundingRateTimestamp': '1746086400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000048',
    'fundingRateTimestamp': '1746057600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000029',
    'fundingRateTimestamp': '1746028800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009197',
    'fundingRateTimestamp': '1746000000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002275',
    'fundingRateTimestamp': '1745971200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001268',
    'fundingRateTimestamp': '1745942400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003872',
    'fundingRateTimestamp': '1745913600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00004385',
    'fundingRateTimestamp': '1745884800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000589',
    'fundingRateTimestamp': '1745856000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005621',
    'fundingRateTimestamp': '1745827200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001103',
    'fundingRateTimestamp': '1745798400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003295',
    'fundingRateTimestamp': '1745769600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001749',
    'fundingRateTimestamp': '1745740800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00006573',
    'fundingRateTimestamp': '1745712000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004978',
    'fundingRateTimestamp': '1745683200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001459',
    'fundingRateTimestamp': '1745654400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00007485',
    'fundingRateTimestamp': '1745625600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004921',
    'fundingRateTimestamp': '1745596800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003245',
    'fundingRateTimestamp': '1745568000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00008908',
    'fundingRateTimestamp': '1745539200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000618',
    'fundingRateTimestamp': '1745510400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0000149',
    'fundingRateTimestamp': '1745481600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003794',
    'fundingRateTimestamp': '1745452800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002238',
    'fundingRateTimestamp': '1745424000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005975',
    'fundingRateTimestamp': '1745395200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002647',
    'fundingRateTimestamp': '1745366400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001936',
    'fundingRateTimestamp': '1745337600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004038',
    'fundingRateTimestamp': '1745308800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003961',
    'fundingRateTimestamp': '1745280000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009109',
    'fundingRateTimestamp': '1745251200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1745222400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001937',
    'fundingRateTimestamp': '1745193600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.0000766',
    'fundingRateTimestamp': '1745164800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001807',
    'fundingRateTimestamp': '1745136000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007048',
    'fundingRateTimestamp': '1745107200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1745078400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006867',
    'fundingRateTimestamp': '1745049600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001215',
    'fundingRateTimestamp': '1745020800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00005146',
    'fundingRateTimestamp': '1744992000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000296',
    'fundingRateTimestamp': '1744963200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003447',
    'fundingRateTimestamp': '1744934400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001058',
    'fundingRateTimestamp': '1744905600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000812',
    'fundingRateTimestamp': '1744876800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000984',
    'fundingRateTimestamp': '1744848000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001926',
    'fundingRateTimestamp': '1744819200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00009053',
    'fundingRateTimestamp': '1744790400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00006198',
    'fundingRateTimestamp': '1744761600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007167',
    'fundingRateTimestamp': '1744732800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1744704000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000392',
    'fundingRateTimestamp': '1744675200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003854',
    'fundingRateTimestamp': '1744646400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00005162',
    'fundingRateTimestamp': '1744617600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003415',
    'fundingRateTimestamp': '1744588800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000389',
    'fundingRateTimestamp': '1744560000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001214',
    'fundingRateTimestamp': '1744531200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007698',
    'fundingRateTimestamp': '1744502400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001472',
    'fundingRateTimestamp': '1744473600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000906',
    'fundingRateTimestamp': '1744444800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00006951',
    'fundingRateTimestamp': '1744416000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1744387200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004989',
    'fundingRateTimestamp': '1744358400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003007',
    'fundingRateTimestamp': '1744329600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004691',
    'fundingRateTimestamp': '1744300800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1744272000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009218',
    'fundingRateTimestamp': '1744243200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1744214400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002068',
    'fundingRateTimestamp': '1744185600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002267',
    'fundingRateTimestamp': '1744156800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003545',
    'fundingRateTimestamp': '1744128000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00007245',
    'fundingRateTimestamp': '1744099200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000902',
    'fundingRateTimestamp': '1744070400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003657',
    'fundingRateTimestamp': '1744041600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00003202',
    'fundingRateTimestamp': '1744012800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000125',
    'fundingRateTimestamp': '1743984000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000377',
    'fundingRateTimestamp': '1743955200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009894',
    'fundingRateTimestamp': '1743926400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009173',
    'fundingRateTimestamp': '1743897600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003366',
    'fundingRateTimestamp': '1743868800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009739',
    'fundingRateTimestamp': '1743840000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009537',
    'fundingRateTimestamp': '1743811200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003029',
    'fundingRateTimestamp': '1743782400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00009307',
    'fundingRateTimestamp': '1743753600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.0001',
    'fundingRateTimestamp': '1743724800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000899',
    'fundingRateTimestamp': '1743696000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001376',
    'fundingRateTimestamp': '1743667200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002095',
    'fundingRateTimestamp': '1743638400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002791',
    'fundingRateTimestamp': '1743609600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00002533',
    'fundingRateTimestamp': '1743580800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002346',
    'fundingRateTimestamp': '1743552000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00001751',
    'fundingRateTimestamp': '1743523200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002705',
    'fundingRateTimestamp': '1743494400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00011844',
    'fundingRateTimestamp': '1743465600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000319',
    'fundingRateTimestamp': '1743436800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00002713',
    'fundingRateTimestamp': '1743408000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00000311',
    'fundingRateTimestamp': '1743379200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000413',
    'fundingRateTimestamp': '1743350400000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00004333',
    'fundingRateTimestamp': '1743321600000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00004207',
    'fundingRateTimestamp': '1743292800000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00000668',
    'fundingRateTimestamp': '1743264000000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '-0.00001692',
    'fundingRateTimestamp': '1743235200000'},
   {'symbol': 'BTCUSDT',
    'fundingRate': '0.00003739',
    'fundingRateTimestamp': '1743206400000'},
   {'symbol': 'BTCUSDT',

In [52]:
data["result"]["list"][-1]["fundingRateTimestamp"]

'1742976000000'

In [45]:
df = pd.DataFrame(data["result"]["list"])

df["fundingRateTimestamp"] = pd.to_datetime(
    pd.to_numeric(df["fundingRateTimestamp"]),
    unit="ms",
    utc=True
)

In [46]:
df

      symbol  fundingRate      fundingRateTimestamp
0    BTCUSDT       0.0001 2025-05-31 16:00:00+00:00
1    BTCUSDT       0.0001 2025-05-31 08:00:00+00:00
2    BTCUSDT       0.0001 2025-05-31 00:00:00+00:00
3    BTCUSDT       0.0001 2025-05-30 16:00:00+00:00
4    BTCUSDT   0.00009532 2025-05-30 08:00:00+00:00
..       ...          ...                       ...
195  BTCUSDT  -0.00003998 2025-03-27 16:00:00+00:00
196  BTCUSDT     0.000047 2025-03-27 08:00:00+00:00
197  BTCUSDT  -0.00001904 2025-03-27 00:00:00+00:00
198  BTCUSDT  -0.00004927 2025-03-26 16:00:00+00:00
199  BTCUSDT   0.00007133 2025-03-26 08:00:00+00:00

[200 rows x 3 columns]

## 4) start_time, end_time

In [5]:
start_time = "2025-03-29 00:00:00"
end_time = "2025-05-31 23:59:59"

start_time = pd.to_datetime(start_time, utc=True)
start_time_ms = int(start_time.timestamp() * 1000)

end_time = pd.to_datetime(end_time, utc=True)
end_time_ms = int(end_time.timestamp() * 1000)

In [6]:
from pybit.unified_trading import HTTP
session = HTTP()
data = session.get_funding_rate_history(
    category="linear",
    symbol="BTCUSDT",
    startTime=start_time_ms,
    endTime=end_time_ms
)

df = pd.DataFrame(data["result"]["list"])

df["fundingRateTimestamp"] = pd.to_datetime(
    pd.to_numeric(df["fundingRateTimestamp"]),
    unit="ms",
    utc=True
)

df

      symbol  fundingRate      fundingRateTimestamp
0    BTCUSDT       0.0001 2025-05-31 16:00:00+00:00
1    BTCUSDT       0.0001 2025-05-31 08:00:00+00:00
2    BTCUSDT       0.0001 2025-05-31 00:00:00+00:00
3    BTCUSDT       0.0001 2025-05-30 16:00:00+00:00
4    BTCUSDT   0.00009532 2025-05-30 08:00:00+00:00
..       ...          ...                       ...
187  BTCUSDT  -0.00004333 2025-03-30 08:00:00+00:00
188  BTCUSDT   0.00004207 2025-03-30 00:00:00+00:00
189  BTCUSDT   0.00000668 2025-03-29 16:00:00+00:00
190  BTCUSDT  -0.00001692 2025-03-29 08:00:00+00:00
191  BTCUSDT   0.00003739 2025-03-29 00:00:00+00:00

[192 rows x 3 columns]

## 5) Prueba

In [8]:
from app.sources.bybit.client import create_client
from app.sources.bybit.funding_rates_source import fetch_get_funding_rate_history
import pandas as pd

client = create_client()

end_time = "2026-07-31 23:59:59"
start_time = "2026-06-11 00:00:00"


start_time = pd.to_datetime(start_time, utc=True)
start_time_ms = int(start_time.timestamp() * 1000)

end_time = pd.to_datetime(end_time, utc=True)
end_time_ms = int(end_time.timestamp() * 1000)


rows = fetch_get_funding_rate_history(
    client=client,
    category="linear",
    symbol="BTCUSDT",
    #end_time=end_time_ms,
    start_time=start_time_ms,
    #limit=445
)

df = pd.DataFrame(rows)
df["fundingRateTimestamp"] = pd.to_datetime(
    pd.to_numeric(df["fundingRateTimestamp"]),
    unit="ms",
    utc=True
)
print(len(df))
df

202

      symbol  fundingRate      fundingRateTimestamp
0    BTCUSDT   0.00000656 2026-08-17 00:00:00+00:00
1    BTCUSDT   0.00003034 2026-08-16 16:00:00+00:00
2    BTCUSDT   0.00001182 2026-08-16 08:00:00+00:00
3    BTCUSDT    0.0000301 2026-08-16 00:00:00+00:00
4    BTCUSDT   0.00004403 2026-08-15 16:00:00+00:00
..       ...          ...                       ...
197  BTCUSDT   0.00002498 2026-06-12 08:00:00+00:00
198  BTCUSDT   0.00008605 2026-06-12 00:00:00+00:00
199  BTCUSDT   0.00006345 2026-06-11 16:00:00+00:00
200  BTCUSDT   0.00009561 2026-06-11 08:00:00+00:00
201  BTCUSDT  -0.00000813 2026-06-11 00:00:00+00:00

[202 rows x 3 columns]